### PR TITLE
Add scaling and transition effect to social icons in the footer

### PR DESCRIPTION
**Pull request by bEluga0000**
## Checklist
- [x] I have read and agree to abide by the [Code of Conduct] 
- [x] I have read and followed the [Contributing Guidelines]

### CODE REVIEW

**Comment by kamalika0363** [comment]
LGTM!!
Good Job @bEluga0000

**Comment by bEluga0000** [comment]
@kamalika0363 Is this repo come under Hacktober Fest

**Comment by kamalika0363** [comment]
> @kamalika0363 Is this repo come under Hacktober Fest 2023

yes it does!

**Comment by bEluga0000** [comment]
Is it going to be okay  if  i try to do some Styling to the page

**Pull request merged**
